CREATE DATABASE SpMedGroup_Manha;

Use SpMedGroup_Manha;

CREATE TABLE Estado(
IDEstado INT PRIMARY KEY IDENTITY,
NomeEstado VARCHAR(255) NOT NULL
);
GO

CREATE TABLE Cidade(
IDCidade INT PRIMARY KEY IDENTITY,
NomeCidade VARCHAR(255) NOT NULL,
IDEstado INT FOREIGN KEY REFERENCES Estado (IDEstado)
);
GO

CREATE TABLE Clinica(
IDClinica INT PRIMARY KEY IDENTITY,
NomeClinica VARCHAR(255) NOT NULL,
CNPJ CHAR(14) NOT NULL UNIQUE,
RazaoSocial VARCHAR(150) NOT NULL,
Logradouro VARCHAR(200) NOT NULL,
Bairro VARCHAR(150) NOT NULL,
HorarioI DATETIME NOT NULL,
HorarioF DATETIME NOT NULL,
IDCidade INT FOREIGN KEY REFERENCES Cidade (IDCidade)
);
GO

CREATE TABLE AreaClinica(
IdAreaClinica INT PRIMARY KEY IDENTITY,
IDClinica INT FOREIGN KEY REFERENCES Clinica (IDClinica)
);
GO

CREATE TABLE PerfilUsuario(
IDPerfilUsuario INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(150) NOT NULL,
);

CREATE TABLE Usuarios(
IDUsuario INT PRIMARY KEY IDENTITY,
Email VARCHAR(100) NOT NULL UNIQUE,
Senha VARCHAR(20) NOT NULL UNIQUE,
IDPerfilUsuario INT FOREIGN KEY REFERENCES PerfilUsuario (IDPerfilUsuario)
);

CREATE TABLE Medicos(
IDMedicos INT PRIMARY KEY IDENTITY,
NomeM VARCHAR(255) NOT NULL,
CRM CHAR(9) NOT NULL UNIQUE,
IDUsuario INT FOREIGN KEY REFERENCES Usuarios (IDUsuario),
IDAreaClinica INT FOREIGN KEY REFERENCES AreaClinica (IDAreaClinica)
);

CREATE TABLE Situacao(
IDSituacao INT PRIMARY KEY IDENTITY,
SituacaoConsulta VARCHAR(100) NOT NULL,
);

CREATE TABLE Prontuario(
IDProntuario INT PRIMARY KEY IDENTITY,
NomeP VARCHAR(255) NOT NULL,
DataNascimento DATETIME NOT NULL,
Telefone VARCHAR(11) NOT NULL,
RG VARCHAR(9) NOT NULL,
CPF VARCHAR(11) NOT NULL,
Peso DECIMAL(3,1) NOT NULL,
Altura DECIMAL(3,2) NOT NULL
);

CREATE TABLE Consultas(
IDConsulta INT PRIMARY KEY IDENTITY,
DataAgendamento DATETIME NOT NULL,
Descricao VARCHAR(200) NOT NULL,
IDProntuario INT FOREIGN KEY REFERENCES Prontuario (IDProntuario) UNIQUE,
IDMedico INT FOREIGN KEY REFERENCES Medicos (IDMedicos) UNIQUE,
IDSituacao INT FOREIGN KEY REFERENCES Situacao (IDSituacao) UNIQUE
);